---
# Deployment of our grafana-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: grafana-service
  replicas: 1
  template:
    metadata:
      labels:
        run: grafana-service
        app.kubernetes.io/name: grafana-service
        app.kubernetes.io/instance: keptn
        app.kubernetes.io/part-of: keptn
        app.kubernetes.io/component: execution-plane
        app.kubernetes.io/version: 0.1.0
    spec:
      containers:
      - name: grafana-service
        image: keptnsandbox/grafana-service:0.1.0 
        ports:
          - containerPort: 8080
        env:
          - name: EVENTBROKER
            value: 'http://event-broker.keptn.svc.cluster.local/keptn'
          - name: CONFIGURATION_SERVICE
            value: 'http://configuration-service.keptn.svc.cluster.local:8080'
          - name: GRAFANA_URL
            value: http://yourgrafana-url
          - name: GRAFANA_TOKEN
            value: yourtoken
          - name: PROMETHEUS_URL
            value: http://yourprometheus-url

      - name: distributor
        image: keptn/distributor:0.8.4
        livenessProbe:
          httpGet:
            path: /health
            port: 10999
          initialDelaySeconds: 5
          periodSeconds: 5
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "16Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
          - name: PUBSUB_URL
            value: 'nats://keptn-nats-cluster'
          - name: PUBSUB_TOPIC
            value: 'sh.keptn.event.monitoring.configure'
          - name: PUBSUB_RECIPIENT
            value: '127.0.0.1'
          - name: VERSION
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: 'metadata.labels[''app.kubernetes.io/version'']'
          - name: K8S_DEPLOYMENT_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: 'metadata.labels[''app.kubernetes.io/name'']'
          - name: K8S_POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: K8S_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
      serviceAccountName: keptn-default

---
# Expose grafana-service via Port 8080 within the cluster
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: keptn
  labels:
    run: grafana-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: grafana-service
